### ISSUE TITLE
ABBYY account password in plaintext

### ISSUE THREAD

**Issue by pallih** [pdfliberation/Jersey-City-Budget-PDF-Liberation#1]
The ABBYY OCR SDK password is in plaintext here: https://github.com/pdfliberation/Jersey-City-Budget-PDF-Liberation/blob/master/AbbyyOnlineSdk.py#L35

I suggest moving it to a config file and excluding that file from the project via .gitignore.

**Comment by adlukasiak** [comment]
Thanks! I reset the password and will make the suggested change later today.

Anna D Lukasiak
Information Technology
201-577-2645
alukasiak@gmail.com
- www.linkedin.com/in/annalukasiak/

**Comment by joffemd** [comment]
The Abbyy cloud OCR trial expires on Saturday, January 25.  This means that the page limit will drop from 5050 pages to 50 pages.
